
Debug=true
Emu=false
KlineInterval="15m"

[Key]
# practical
ApiKey="Jlt16Gp7ejTVy26xCp6z0l44f74ZhmJFu7infiKW93Va2bqJTv5tB1Gx4h0jK3ks"
SecretKey="hgGzCFKl84xQfaWRbj7kmJsCQOqG6NlOVAoFLAnguO0RZg0Imo0dDR8kSVv8AAZz"
