
# todo
TakeProfit=1.0
StopLimit=1.2
MaxLeverage=true
Debug=true
Emu=false
KlineInterval="15m"
Qty="0.08"
Symbol="BCHUSDT"

[key]
# practical
#ApiKey="Jlt16Gp7ejTVy26xCp6z0l44f74ZhmJFu7infiKW93Va2bqJTv5tB1Gx4h0jK3ks"
#SecretKey="hgGzCFKl84xQfaWRbj7kmJsCQOqG6NlOVAoFLAnguO0RZg0Imo0dDR8kSVv8AAZz"

# y
ApiKey="25SFJeqQGvI5Dgklhgse3bFtYpysvcFtGZK2mgUvpImSgJRSMENvvu8QMlTT1atF"
SecretKey="0vFUpXy52nNp9bLB5sQVzU4vuocmqClupHf8l4DaiHUusBNTKRrIawveRMXUytQY"

[strategy]
PyramidSegments=20

[redis]
host="45.76.217.200"
port=6379
password="huangshuai"
