name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o main cmd/main.go

#    - name: deploy
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.SERVER_IP }}
#        username: ${{ secrets.SERVER_USERNAME }}
#        password: ${{ secrets.SERVER_PASSWORD }}
#        script: ls

    - name: deploy copy main
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "main"
        target: "~/binance"



